import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

export default function Home(){
 const [test,setTest]=useState<{title:string;scheduled_for:string}|null>(null);
 useEffect(()=>{let live=true;supabase.from("national_tests").select("title,scheduled_for").eq("status","scheduled").order("scheduled_for",{ascending:true}).limit(1).maybeSingle().then(({data})=>{if(live)setTest(data)});return()=>{live=false}},[]);
 return <div className="min-h-screen"><header className="max-w-editorial mx-auto px-6 md:px-10 h-20 flex items-center justify-between relative z-10"><Link to="/" className="brand">RAW</Link><nav className="flex gap-7 text-sm"><a href="#system" className="hidden sm:block link">The system</a><Link to="/login" className="link">Log in</Link><Link to="/signup" className="button">Start</Link></nav></header>
 <section className="relative overflow-hidden min-h-[74vh] flex items-center border-b hairline"><div className="hero-live" aria-hidden="true"/><div className="relative max-w-editorial mx-auto px-6 md:px-10 py-24 w-full"><p className="eyebrow">REAL ACADEMIC WORK / 100% FREE</p><h1 className="display text-6xl md:text-8xl leading-[.92] max-w-5xl mt-6">Study without<br/>the noise.</h1><p className="muted mt-8 max-w-xl text-lg leading-8">A high-end self-study environment for learning, practice, revision, testing and understanding what actually needs work.</p><div className="mt-10 flex gap-5 items-center"><Link to="/signup" className="button">Begin studying</Link><a href="#system" className="link text-sm">Explore RAW ↓</a></div></div></section>
 <section id="system" className="max-w-editorial mx-auto px-6 md:px-10 py-28"><div className="grid md:grid-cols-5 gap-8">{[["01","LEARN","Concepts, lessons and verified material."],["02","PRACTICE","Unlimited practice built from real content."],["03","TEST","Topic tests to full-length exams."],["04","REVISE","Mistakes, recall and spaced revision."],["05","MEASURE","Performance based on what you actually do."]].map(([n,t,c])=><div className="border-t hairline pt-5" key={t}><span className="eyebrow">{n}</span><h2 className="display text-2xl mt-4">{t}</h2><p className="muted mt-2 text-sm leading-6">{c}</p></div>)}</div></section>
 <section className="border-t hairline"><div className="max-w-editorial mx-auto px-6 md:px-10 py-28"><p className="eyebrow">RAW NATIONAL</p><h2 className="display text-5xl mt-4">One serious test.<br/>Every week.</h2><div className="mt-12 max-w-2xl border-t border-b hairline py-6">{test?<><strong className="font-display text-2xl">{test.title}</strong><p className="muted mt-2 text-sm">{new Date(test.scheduled_for).toLocaleString()}</p></>:<p className="muted text-sm">No verified national test is scheduled yet.</p>}</div></div></section>
 <section className="border-t hairline"><div className="max-w-editorial mx-auto px-6 md:px-10 py-28 flex flex-col md:flex-row md:items-end justify-between gap-10"><div><p className="eyebrow">NO DEMO DATA</p><h2 className="display text-5xl mt-4 max-w-2xl">If RAW doesn't know it,<br/>RAW won't pretend.</h2></div><Link to="/signup" className="button shrink-0">Create free account</Link></div></section>
 <footer className="border-t hairline"><div className="max-w-editorial mx-auto px-6 md:px-10 py-8 flex justify-between text-xs muted"><span>© {new Date().getFullYear()} RAW</span><span>Real Academic Work</span></div></footer></div>
}
